name: Ping Landing Page

on:
  schedule:
    - cron: '*/14 18-21 * * 1-5' # Every 14 minutes between 18:00 and 21:00 on weekdays

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping server
        run: curl -s https://dev-landing-page-jet.carlos-brandao.dev.br/ > /dev/null
